### ISSUE TITLE
Linux Server Will Not Start

### ISSUE THREAD

**Issue by mprofitt** [NFive/NFive#19]
Ubuntu 18.04
Mono 5.20.19
Mariadb 10.1.40

Installed NFive as described and when starting with the command 'mono nfpm.exe start' I get the error... 
```
An unhandled application error has occured:
Unable to locate FiveM server in the directory tree.
```
The server folder and all contents are there.
Mariadb does not like this is her /etc/mysql/conf.d/mysql.cnf file
```
[mysqld]
character-set-server=utf8mb4
collation-server=utf8mb4_unicode_520_ci
```
When I run the command 'mariadb --version, she replies with mariadb: unknown variable 'character-set-server=utf8mb4'

Thanks

**Comment by JoeBiellik** [comment]
Thanks for the info, it looks like you have two issues here.

The first issue is probably because you are not running the start command from inside the server directory. If you run `mono nfpm.exe status` you should get some more information, but its likely that you just need to change to inside the `server` directory before running start. If you can't get it working then please paste your directory listing showing nfpm and the server files here.

I believe the MariaDB error is because you are using an older version, we wrote the docs for the latest 10.3 version. 10.1 should work fine with NFive but I believe the config option is different in older versions. Try replacing `character-set-server` with `default-character-set` and see if that helps.

**Comment by mprofitt** [comment]
You was right. I changed to server directory and ran nfpm.exe and the server starts.
/home/mprofitt/nfive/server

I tried to install Nfive/plugin-start and get this error. 
```
$ mono /home/mprofitt/nfive/nfpm.exe install Nfive/plugin-start
https://hub.nfive.io/api/project/Nfive/plugin-start.json
Error Nfive/plugin-start not found.
```
I have installed this previously on Windows (without the database) and it worked fine.
Thanks for your help.

**Comment by JoeBiellik** [comment]
Plugin names are case sensitive: `install NFive/plugin-start`
