### ISSUE TITLE
Standard Resources?

### ISSUE THREAD

**Issue by steveski** [NFive/NFive#44]
Is it still possible to use existing non NFive resources?

**Comment by TheFuseGamer** [comment]
As long as they don't interfere with the NFive plugins I don't see why they wouldn't work.

**Comment by IgiCodes** [comment]
Officially, we do not support the use of NFive with other mods due to NFive being its own mod ecosystem and us not wanting to make compromises for the sake of supporting other systems.

However, unofficially there is no reason you can't use other resources alongside NFive. It's fairly self-contained and shouldn't conflict with much so you're welcome to try it and see how you get on.

**Comment by steveski** [comment]
> As long as they don't interfere with the NFive plugins I don't see why they wouldn't work.

I did use the ocrp_postal map which is purely stream folder textures, but it won't load and reports that it couldn't on launch. Do the resources just go at the same level as the nfive resource and add the ensure ... statement like normal or do they have to go some place else?

**Comment by IgiCodes** [comment]
As far as FiveM is concerned, NFive is just another resource. It makes no changes to the way fivem loads resources because it literally can't. Have you tried loading the resource with NFive disabled to make sure you're setting it up correctly?

I'm afraid I can't really offer much more support on something non-nfive as it's out of my hands.
You might be better off joining our discord (https://discord.nfive.io/) and seeing if anyone can help there as people are happy to discuss and help with non-nfive stuff there also.
